sonar.projectKey=tejavamsi777-stack_tgicet-counselling-simulator
sonar.organization=tejavamsi777-stack
sonar.sources=client/src,server/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/public/**,**/*.pdf,**/*.txt,**/*.xlsx,**/*.json,**/*.map,client/src/data/**,server/src/data/**,server/scripts/**
sonar.javascript.environments=browser,node
sonar.cpd.exclusions=**/data/**,**/*.json
