export const exams = [
  {
    id: "ap-eapcet",
    slug: "ap-eapcet",
    shortName: "AP EAPCET",
    state: "Andhra Pradesh",
    name: "Andhra Pradesh Engineering, Agriculture & Pharmacy Common Entrance Test",
    description: "Engineering, agriculture and pharmacy admissions guidance.",
    programs: ["ENGINEERING", "AGRICULTURE", "PHARMACY"],
    predictorAvailable: true,
    counsellingAvailable: true,
    status: "available",
  },


  {
    id: "tg-eapcet",
    slug: "tg-eapcet",
    shortName: "TG EAPCET",
    state: "Telangana",
    name: "Telangana Engineering, Agriculture & Pharmacy Common Entrance Test",
    description: "Engineering, agriculture and pharmacy admissions guidance.",
    programs: ["ENGINEERING", "AGRICULTURE", "PHARMACY"],
    predictorAvailable: true,
    counsellingAvailable: true,
    status: "available",
  },
  {
    id: "tg-icet",
    slug: "tg-icet",
    shortName: "TG ICET",
    state: "Telangana",
    name: "Telangana Integrated Common Entrance Test",
    description: "Admissions guidance for MBA and MCA programmes in Telangana.",
    programs: ["MBA", "MCA"],
    predictorAvailable: true,
    counsellingAvailable: true,
    status: "available",
    legacyPath: "/icet",
  },
  {
    id: "tg-ecet",
    slug: "tg-ecet",
    shortName: "TG ECET",
    state: "Telangana",
    name: "Telangana Engineering Common Entrance Test",
    description: "Lateral-entry engineering & pharmacy admissions guidance for diploma holders.",
    programs: ["B.E.", "B.TECH", "B.PHARMACY"],
    predictorAvailable: true,
    counsellingAvailable: true,
    status: "available",
  },
  {
    id: "tg-polycet",
    slug: "tg-polycet",
    shortName: "TG POLYCET",
    state: "Telangana",
    name: "Telangana Polytechnic Common Entrance Test",
    description: "Polytechnic & Diploma admissions guidance for 10th / SSC passed candidates.",
    programs: ["DIPLOMA (ENGG / TECH / AGRI)"],
    predictorAvailable: true,
    counsellingAvailable: true,
    status: "available",
  },
  {
    id: "tg-pgecet",
    slug: "tg-pgecet",
    shortName: "TG PGECET",
    state: "Telangana",
    name: "Telangana Post Graduate Engineering Common Entrance Test",
    description: "Postgraduate M.Tech, M.E. & M.Arch admissions guidance.",
    programs: ["M.E.", "M.TECH", "M.ARCH", "M.PHARMACY"],
    predictorAvailable: true,
    counsellingAvailable: true,
    status: "available",
  },
  { id: "tg-edcet", slug: "tg-edcet", shortName: "TG EDCET", state: "Telangana", name: "Telangana Education Common Entrance Test", description: "B.Ed. admissions guidance.", programs: ["B.ED."], predictorAvailable: false, counsellingAvailable: false, status: "coming-soon" },
  { id: "tg-lawcet", slug: "tg-lawcet", shortName: "TG LAWCET", state: "Telangana", name: "Telangana Law Common Entrance Test", description: "Law admissions guidance.", programs: ["LL.B. 3 YEAR", "LL.B. 5 YEAR"], predictorAvailable: false, counsellingAvailable: false, status: "coming-soon" },
  { id: "tg-cpget", slug: "tg-cpget", shortName: "TG CPGET", state: "Telangana", name: "Telangana Common Post Graduate Entrance Tests", description: "Postgraduate programme admissions guidance.", programs: ["M.A.", "M.SC.", "M.COM."], predictorAvailable: false, counsellingAvailable: false, status: "coming-soon" },
  { id: "tg-pglcet", slug: "tg-pglcet", shortName: "TG PGLCET", state: "Telangana", name: "Telangana Post Graduate Law Common Entrance Test", description: "LL.M. admissions guidance.", programs: ["LL.M."], predictorAvailable: false, counsellingAvailable: false, status: "coming-soon" },
  { id: "tg-pecet", slug: "tg-pecet", shortName: "TG PECET", state: "Telangana", name: "Telangana Physical Education Common Entrance Test", description: "Physical education admissions guidance.", programs: ["B.P.ED.", "D.P.ED."], predictorAvailable: false, counsellingAvailable: false, status: "coming-soon" },
];

export const getExamBySlug = (slug) => exams.find((exam) => exam.slug === slug);
